declare 
	v_count NUMBER;
	v_stat VARCHAR2(32767);
begin
	SELECT COUNT(*) INTO v_count
	FROM USER_TABLES WHERE TABLE_NAME = 'DOCUMENT_SCAN_AI_FIELD_TYPES';
	if v_count = 0 then 
		v_stat := q'[
CREATE TABLE DOCUMENT_SCAN_AI_FIELD_TYPES
(id             	NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT DOCU_SCAN_AI_FIELD_TYPES_PK PRIMARY KEY NOT NULL
,Document_type  	VARCHAR2(50)  NOT NULL
,field_label        VARCHAR2(50)  NOT NULL
,Description        VARCHAR2(300)
,API_Response_Value VARCHAR2(300)
,value_type         VARCHAR2(50)
,format_mask		VARCHAR2(50)
,field_name_eng 	VARCHAR2(100)	-- Form field name in english language
,field_name_deu 	VARCHAR2(100)	-- Form field name in german language
,page_item_name 	VARCHAR2(50)	-- APEX Page Item Name for copy into form
,config_id         	NUMBER DEFAULT ON NULL 1 NOT NULL
,CONSTRAINT DOCU_SCAN_AI_FIELD_TYPES_UK UNIQUE (config_id, Document_type, field_label, format_mask) 
,CONSTRAINT DOCU_SCAN_AI_FIELD_TYPES_CONF_FK FOREIGN KEY (config_id) REFERENCES DOCUMENT_SCAN_AI_CONFIG
)
]';
		EXECUTE IMMEDIATE v_Stat;
	end if;
	SELECT COUNT(*) INTO v_count
	FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DOCUMENT_SCAN_AI_FIELD_TYPES' AND COLUMN_NAME = 'FIELD_NAME_ENG';
	if v_count = 0 then 
		v_stat := q'[
		ALTER TABLE DOCUMENT_SCAN_AI_FIELD_TYPES ADD
		(
			field_name_eng 		VARCHAR2(100)
			,field_name_deu 	VARCHAR2(100)
			,page_item_name 	VARCHAR2(50)
		)
		]';
		EXECUTE IMMEDIATE v_Stat;
	end if;

	SELECT COUNT(*) INTO v_count
	FROM USER_TABLES WHERE TABLE_NAME = 'DOCUMENT_SCAN_AI_FIELD_ALIAS';
	if v_count = 0 then 
		v_stat := q'[
CREATE TABLE DOCUMENT_SCAN_AI_FIELD_ALIAS
(id             	NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT DOCU_SCAN_AI_FIELD_ALIAS_PK PRIMARY KEY NOT NULL
,Document_type  	VARCHAR2(50)  NOT NULL
,field_label        VARCHAR2(50)  NOT NULL
,field_alias        VARCHAR2(300) NOT NULL
,language_code      VARCHAR2(10) DEFAULT ON NULL 'ENG' NOT NULL 
,config_id         	NUMBER DEFAULT ON NULL 1 NOT NULL
,CONSTRAINT DOCU_SCAN_AI_FIELD_ALIAS_UK UNIQUE (config_id, Document_type, language_code, field_label, field_alias) 
,CONSTRAINT DOCU_SCAN_AI_FIELD_ALIAS_CONF_FK FOREIGN KEY (config_id) REFERENCES DOCUMENT_SCAN_AI_CONFIG
)
]';
		EXECUTE IMMEDIATE v_Stat;
	end if;

	SELECT COUNT(*) INTO v_count
	FROM USER_TABLES WHERE TABLE_NAME = 'DOCUMENT_SCAN_AI_LINE_ITEM_TYPES';
	if v_count = 0 then 
		v_stat := q'[
CREATE TABLE DOCUMENT_SCAN_AI_LINE_ITEM_TYPES
(id             	NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT DOCU_SCAN_AI_LINE_ITEM_TYPES_PK PRIMARY KEY NOT NULL
,Document_type  	VARCHAR2(50)  NOT NULL
,Line_Item        	VARCHAR2(50)  NOT NULL
,Description        VARCHAR2(300)
,value_type         VARCHAR2(50)
,config_id         	NUMBER DEFAULT ON NULL 1  NOT NULL
,CONSTRAINT DOCU_SCAN_AI_LINE_ITEM_TYPES_UK UNIQUE (config_id, Document_type, Line_Item) 
,CONSTRAINT DOCU_SCAN_AI_LINE_ITEM_TYPES_CONF_FK FOREIGN KEY (config_id) REFERENCES DOCUMENT_SCAN_AI_CONFIG
)
]';
		EXECUTE IMMEDIATE v_Stat;
	end if;

	/* table for languages with parameters for TO_NUMBER and TO_DATE */
	SELECT COUNT(*) INTO v_count
	FROM USER_TABLES WHERE TABLE_NAME = 'DOCUMENT_SCAN_AI_LANGUAGES';
	if v_count = 0 then 
		v_stat := q'[
CREATE TABLE DOCUMENT_SCAN_AI_LANGUAGES 
(id             	NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT DOCUMENT_SCAN_AI_LANGUAGES_PK PRIMARY KEY NOT NULL
,iso_code 			VARCHAR2(10) NOT NULL
,language_name 		VARCHAR2(50) NOT NULL			-- nls_date_language IN ( select INITCAP(VALUE) Language from  v$nls_valid_values where parameter = 'LANGUAGE' )
,common_date_format VARCHAR2(20) NOT NULL
,common_number_format VARCHAR2(20) NOT NULL
,nls_date_language  VARCHAR2(20) NOT NULL			-- nls_date_language IN ( select VALUE from  v$nls_valid_values where parameter = 'LANGUAGE' )
,territory 			VARCHAR2(20) NOT NULL			-- territory IN ( select VALUE from  v$nls_valid_values where parameter = 'TERRITORY' )
,nls_numeric_characters VARCHAR2(20) NOT NULL
,nls_currency 		VARCHAR2(20) NOT NULL
,nls_iso_currency 	VARCHAR2(20) NOT NULL
,config_id 			NUMBER DEFAULT ON NULL 1 NOT NULL
,CONSTRAINT DOCU_SCAN_AI_LANGUAGES_CONF_FK FOREIGN KEY (config_id) REFERENCES DOCUMENT_SCAN_AI_CONFIG
)
]';
		EXECUTE IMMEDIATE v_Stat;
	end if;
end;
/

DELETE FROM DOCUMENT_SCAN_AI_FIELD_TYPES WHERE config_id = 1;
DELETE FROM DOCUMENT_SCAN_AI_LINE_ITEM_TYPES WHERE config_id = 1;

-- Receipts --
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type)
VALUES ('RECEIPT', 'MerchantName',	'The name of the merchant issuing the receipt.', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type)
VALUES ('RECEIPT', 'MerchantPhoneNumber',	'The telephone number of the merchant.', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type)
VALUES ('RECEIPT', 'MerchantAddress',	'The address of the merchant.', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Format_Mask)
VALUES ('RECEIPT', 'TransactionDate',	'The date the receipt was issued.', 'DATE', 'MM/DD/RRRR');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Format_Mask)
VALUES ('RECEIPT', 'TransactionTime',	'The time the receipt was issued.', 'DATE', 'HH24:MI:SS');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Format_Mask)
VALUES ('RECEIPT', 'TransactionTime',	'The time the receipt was issued.', 'DATE', 'HH12:MIPM');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type)
VALUES ('RECEIPT', 'Total',	'The total amount of the receipt, after all charges and taxes have been applied.', 'NUMBER');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type)
VALUES ('RECEIPT', 'SubTotal',	'The subtotal before taxes.', 'NUMBER');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type)
VALUES ('RECEIPT', 'Tax',	'Any sales taxes.', 'NUMBER');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type)
VALUES ('RECEIPT', 'Tip',	'The amount of tip given by the purchaser.', 'NUMBER');
COMMIT;

INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('RECEIPT', 'ItemName',	'Name of the item.', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('RECEIPT', 'ItemPrice',	'Unit price of the item.', 'NUMBER');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('RECEIPT', 'ItemQuantity',	'The number of each item purchased.', 'NUMBER');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('RECEIPT', 'ItemTotalPrice',	'The total price of the line item.', 'NUMBER');
COMMIT;


INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'CustomerName',	'Name of invoiced customer.', 'STRING', 'Customer Name', 'Kundenname', 'P4_MANDANTENNAME');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'CustomerId',	'Customer reference identifier.', 'ALPHANUM', 'Customer Id', 'Kunden-Nr.', 'P4_BANKKUNDENNR');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'PurchaseOrder',	'Purchase order number.', 'STRING', 'Purchase Order', 'Bestellnummer', null);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'InvoiceId',	'Identifier for the specific invoice.', 'ALPHANUM', 'Invoice Id', 'RechnungsId', 'P4_POSTEN_NR');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'InvoiceDate',	'Date of issue on the invoice.', 'DATE', 'Invoice Date', 'Rechnungsdatum', 'P4_BELEGDATUM');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'DueDate',	'Date when payment is due on this invoice.', 'DATE', 'Due Date', 'Fälligkeitsdatum', 'P4_FAELLIGKEITSDATUM');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'VendorName',	'Name of vendor.', 'STRING', 'Vendor Name', 'Lieferantenname', 'P4_MANDANTENNAME');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'VendorNameLogo',	'Logo of vendor.', 'STRING', 'Vendor Logo', 'Lieferanten Logo', 'P4_MANDANTENNAME');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'VendorTaxId',	'Tax-Id of vendor.', 'ALPHANUM', 'Vendor tax id', 'Lieferantensteuer ID', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'VendorAddress',	'Vendor mailing address.', 'STRING', 'Vendor address', 'Lieferantenadresse', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'VendorAddressRecipient',	'Name referenced with the VendorAddress.', 'STRING', 'Vendor address recipient', 'Lieferantenadresse Empfänger', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'CustomerAddress',	'Mailing address for the Customer.', 'STRING', 'Customer address', 'Kundenadresse', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'CustomerAddressRecipient',	'Name referenced with the CustomerAddress.', 'STRING', 'Customer address recipient', 'Kundenadresse Empfänger', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'BillingAddress',	'Explicit billing address for the customer.', 'STRING', 'Billing address', 'Rechnungsadresse', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'BillingAddressRecipient',	'Name referenced with the BillingAddress.', 'STRING', 'Billing address recipient', 'Rechnungsadresse Empfänger', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'ShippingAddress',	'Explicit shipping address for the customer.', 'STRING', 'Shipping address', 'Lieferadresse', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'ShippingAddressRecipient',	'Name referenced with the ShippingAddress.', 'STRING', 'Shipping address recipient', 'Lieferadresse Empfänger', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'PaymentTerm',	'The terms of payment for the invoice.', 'STRING', 'Payment term', 'Zahlungsbedingungen', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'SubTotal',	'Subtotal field identified on this invoice.', 'NUMBER', 'Sub total', 'Zwischensumme Netto', 'P4_GEA_FORDERUNG_NETTO');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'TotalTax',	'Total tax value identified on this invoice.', 'NUMBER', 'Total tax', 'Gesamtsteuer', 'P4_GEA_FORDERUNG_UST');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'TotalVAT',	'Total tax value identified on this invoice.', 'NUMBER', 'Total vat', 'Gesamtmehrwertsteuer', 'P4_GEA_FORDERUNG_UST');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'InvoiceTotal',	'Total charge amount associated with the invoice.', 'NUMBER', 'Invoice total', 'Rechnungsumme Brutto', 'P4_GEAENDERTE_FORDERUNG');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'AmountDue',	'Total amount due to the vendor.', 'NUMBER', 'amount due', 'Fälliger Betrag', 'P4_GEAENDERTE_FORDERUNG');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'ServiceAddress',	'Explicit service address or property address for the customer.', 'STRING', 'Service address', 'Serviceadresse', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'ServiceAddressRecipient',	'Name referenced with the ServiceAddress.', 'STRING', 'Service address recipient', 'Serviceadresse Empfänger', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'RemittanceAddress',	'Explicit remittance or payment address for the customer.', 'STRING', 'Remittance address', 'Zahlungsadresse', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'RemittanceAddressRecipient',	'Name referenced with the RemittanceAddress.', 'STRING', 'Remittance address recipient', 'Zahlungsadresse Empfänger', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'ShippingCost',	'Total shipping or shipping and handling costs associated with an invoice.', 'NUMBER', 'Shipping cost', 'Versandkosten', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'ServiceStartDate',	'First date for the service period.', 'DATE', 'Service start date', 'Service Startdatum', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'ServiceEndDate',	'End date for the service period.', 'DATE', 'Service end date', 'Service Enddatum', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'PreviousUnpaidBalance',	'Explicit previously unpaid balance.', 'NUMBER', 'Previous unpaid balance', 'vorherige unbezahlte Bilanz', NULL);

-- extra custom field labels
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'InvoiceReceiptDate', 'Date of reception of the invoice.', 'DATE', 'Invoice receipt date', 'Rechnungseingangsdatum', 'P4_EINGANGSDATUM');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'InvoicePaidDate',	'Date of payment of the invoice.', 'DATE', 'Invoice paid date', 'Rechnung Bezahldatum', 'P4_ZAHLDATUM');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'VendorEmail',	'Vendor e-mail address.', 'EMAIL', 'Vendor email', 'Lieferanten E-Mail', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'VendorPhone',	'Vendor phone number.', 'PHONE', 'Vendor phone', 'Lieferantentelefon', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'VendorMobil',	'Vendor mobil number.', 'PHONE', 'Vendor mobile', 'Lieferantenmobil', NULL);
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'BankBIC',	'Vendor Bank BIC.', 'SWIFTBIC', 'Bank BIC', 'Bank BIC', 'P4_SWIFT_BIC');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'BankIBAN',	'Vendor Bank IBAN.', 'IBAN', 'Bank IBAN', 'Bank IBAN', 'P4_IBAN');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, Value_Type, Field_Name_Eng, Field_Name_Deu, Page_Item_Name)
VALUES ('INVOICE', 'Ignored',	'Ignored Aliases', 'STRING', '*Ignored', '*Ausgeblendet', NULL);
COMMIT;


------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'Items',	'Concatenation of all other line item values (that is, the entire line of the line item).', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'Name',	'The name listed for a product or service, for example, t-shirt.', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'Amount',	'The amount of the line item.', 'NUMBER');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'Description',	'The text description for the invoice line item, for example, men''s rayon shirt, sizes small, medium, and large.', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'Quantity',	'The quantity for this invoice line item.', 'NUMBER');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'UnitPrice',	'The price per item identified on the invoice.', 'NUMBER');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'ProductCode',	'Product code, product number, or SKU referenced in the line item. For example, 123456.', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'Unit',	'The unit of the line item, for example, kg, lb.', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'Tax',	'Tax explicitly referenced on the line item.', 'NUMBER');
INSERT INTO DOCUMENT_SCAN_AI_LINE_ITEM_TYPES (Document_type, Line_Item, Description, Value_Type)
VALUES ('INVOICE', 'Date',	'Date corresponding to each line item.', 'DATE');
COMMIT;

-- Driver ID --
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('DRIVER_LICENSE', 'FirstName',	'First name (given name) listed on the document.',	'Extracted Text', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('DRIVER_LICENSE', 'LastName',	'Last name (family name) listed on the document.',	'Extracted Text', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('DRIVER_LICENSE', 'Country',	'Country listed on the document.',	'Extracted ISO 3166-1 country code', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type, Format_Mask)
VALUES ('DRIVER_LICENSE', 'BirthDate',	'Date of birth.',	'Date in YYYY/MM/DD format', 'DATE', 'YYYY/MM/DD');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type, Format_Mask)
VALUES ('DRIVER_LICENSE', 'ExpiryDate',	'Date of expiration listed on the document.',	'Date in YYYY/MM/DD format', 'DATE', 'YYYY/MM/DD');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type, Format_Mask)
VALUES ('DRIVER_LICENSE', 'IssueDate',	'Date of issue listed on the document.',	'Date in YYYY/MM/DD format', 'DATE', 'YYYY/MM/DD');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('DRIVER_LICENSE', 'Gender',	'Gender listed on the document.',	'Extracted Text', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('DRIVER_LICENSE', 'DocumentNumber',	'Document identification number.',	'Extracted Text', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('DRIVER_LICENSE', 'Address',	'Address listed on the document.',	'Extracted Text', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('DRIVER_LICENSE', 'Region',	'Region listed on the document. For example, state or territory.',	'Extracted Text', 'STRING');
COMMIT;


-- Passport -- 
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('PASSPORT', 'FirstName',	'First name (given name) listed on the document.',	'Extracted Text', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('PASSPORT', 'LastName',	'Last name (family name) listed on the document.',	'Extracted Text', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('PASSPORT', 'Country',	'Country listed on the document.',	'Extracted ISO 3166-1 country code', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('PASSPORT', 'Nationality',	'Nationality of the document owner.',	'Extracted ISO 3166-1 country code', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type, Format_Mask)
VALUES ('PASSPORT', 'BirthDate',	'Date of birth.',	'Date in YYYY/MM/DD format', 'DATE', 'YYYY/MM/DD');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type, Format_Mask)
VALUES ('PASSPORT', 'ExpiryDate',	'Date of expiration listed on the document.',	'Date in YYYY/MM/DD format', 'DATE', 'YYYY/MM/DD');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('PASSPORT', 'Gender',	'Gender listed on the document.',	'Extracted Text', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('PASSPORT', 'DocumentType',	'Document type, often listed as a single character, such as "P" for passport or "V" for Visa.',	'Extracted Text', 'STRING');
INSERT INTO DOCUMENT_SCAN_AI_FIELD_TYPES (Document_type, Field_label, Description, API_Response_Value, Value_Type)
VALUES ('PASSPORT', 'DocumentNumber',	'Document identification number.',	'Extracted Text', 'STRING');
COMMIT;


/*
insert statements for:
English, French, German, Italian, Spanish, Portuguese, Russian, Polish, Dutch, Swedish, Norwegian, Danish, Finnish, Greek, Turkish, Czech, Hungarian, Romanian, Bulgarian, Serbian, Croatian, Ukrainian, Japanese , Korean , Simplified Chinese, Traditional Chinese, 
*/
DELETE FROM DOCUMENT_SCAN_AI_LANGUAGES WHERE config_id = 1;

INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('ENG', 'English', 'MM/DD/RRRR', '999,999,999.99', 'AMERICAN', 'AMERICA', '.,', '$', 'USD');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('ENG', 'English', 'MM/DD/RRRR', '999,999,999.99', 'AMERICAN', 'AMERICA', '.,', '€', 'EUR');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('ENG', 'English', 'DD-MON-RRRR', '999,999,999.99', 'ENGLISH', 'UNITED KINGDOM', '.,', '£', 'GBP');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('ENG', 'English', 'DD.MM.RRRR', '999.999.999,99', 'ENGLISH', 'GERMANY', ',.','€', 'EUR');

INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('DEU', 'German', 'DD.MM.RRRR', '999.999.999,99', 'GERMAN', 'GERMANY', ',.','€', 'EUR');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('DEU', 'German', 'DD.MM.RRRR', '999 999 999.99', 'GERMAN', 'AUSTRIA', '. ','€', 'EUR');

INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('FRA', 'French', 'DD/MM/RRRR', '999 999 999,99', 'FRENCH', 'FRANCE', ', ','€', 'EUR');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('ITA', 'Italian', 'DD/MM/RRRR', '999.999.999,99', 'ITALIAN', 'ITALY', ',.','€', 'EUR');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('ESP', 'Spanish', 'DD/MM/RRRR', '999.999.999,99', 'SPANISH', 'SPAIN', ',.','€', 'EUR');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('PRT', 'Portuguese', 'DD/MM/RRRR', '999.999.999,99', 'PORTUGUESE', 'PORTUGAL', ',.','€', 'EUR');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('RUS', 'Russian', 'DD.MM.RRRR', '999 999 999,99', 'RUSSIAN', 'RUSSIA', ', ','RUB', 'RUB');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('POL', 'Polish', 'RRRR-MM-DD', '999 999 999,99', 'POLISH', 'POLAND', ', ','zł', 'PLN');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('NLD', 'Dutch', 'DD-MM-RRRR', '999.999.999,99', 'DUTCH', 'THE NETHERLANDS', ',.','€', 'EUR');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('SWE', 'Swedish', 'RRRR-MM-DD', '999 999 999,99', 'SWEDISH', 'SWEDEN', ', ', 'kr', 'SEK');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('NOR', 'Norwegian', 'DD.MM.RRRR', '999 999 999,99', 'NORWEGIAN', 'NORWAY', ', ','kr', 'NOK');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('DNK', 'Danish', 'DD-MM-RRRR', '999.999.999,99', 'DANISH', 'DENMARK', ',.','kr', 'DKK');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('FIN', 'Finnish', 'DD.MM.RRRR', '999 999 999,99', 'FINNISH', 'FINLAND', ', ','€', 'EUR');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('GRC', 'Greek', 'DD/MM/RRRR', '999.999.999,99', 'GREEK', 'GREECE', ',.','€', 'EUR');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('TUR', 'Turkish', 'DD.MM.RRRR', '999.999.999,99', 'TURKISH', 'TURKEY', ',.', 'TL', 'TRY');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('CZE', 'Czech', 'DD.MM.RRRR', '999 999 999,99', 'CZECH', 'CZECH REPUBLIC', ', ','Kč', 'CZK');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('HUN', 'Hungarian', 'RRRR.MM.DD', '999 999 999,99', 'HUNGARIAN', 'HUNGARY', ', ', 'Ft', 'HUF');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('RON', 'Romanian', 'DD/MM/RRRR', '999.999.999,99', 'ROMANIAN', 'ROMANIA', ',.','lei', 'RON');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('BGR', 'Bulgarian', 'DD.MM.RRRR', '999 999 999,99', 'BULGARIAN', 'BULGARIA', ', ','лв', 'BGN');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('SRB', 'Serbian', 'DD.MM.RRRR', '999.999.999,99', 'LATIN SERBIAN', 'SERBIA', ',.','RSD', 'RSD');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('SRB', 'Serbian', 'DD.MM.RRRR', '999.999.999,99', 'LATIN BOSNIAN', 'SERBIA', ',.','RSD', 'RSD');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('HRV', 'Croatian', 'DD.MM.RRRR', '999.999.999,99', 'CROATIAN', 'CROATIA', ',.','kn', 'HRK');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('UKR', 'Ukrainian', 'DD.MM.RRRR', '999 999 999,99', 'UKRAINIAN', 'UKRAINE', ', ','₴', 'UAH');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('JPN', 'Japanese', 'RRRR/MM/DD', '999,999,999.99', 'JAPANESE', 'JAPAN', '.,', '¥', 'JPY');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('KOR', 'Korean', 'RRRR-MM-DD', '999,999,999.99', 'KOREAN', 'SOUTH KOREA', '.,', '₩', 'KRW');  
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('CHS', 'Simplified Chinese', 'RRRR-MM-DD', '999,999,999.99', 'SIMPLIFIED CHINESE', 'CHINA', '.,', '¥', 'CNY');
INSERT INTO document_scan_ai_languages (iso_code, language_name, common_date_format, common_number_format, nls_date_language, territory, nls_numeric_characters, nls_currency, nls_iso_currency)
VALUES ('CHT', 'Traditional Chinese', 'RRRR-MM-DD', '999,999,999.99', 'TRADITIONAL CHINESE', 'TAIWAN', '.,', 'NT$', 'TWD');
COMMIT;


