
GRANT SELECT ON V_DOCUMENT_SCAN_AI_INVOICES TO WECO_TOWER1 WITH GRANT OPTION;
GRANT SELECT ON V_DOCUMENT_SCAN_AI_LINE_ITEM_INVOICE TO WECO_TOWER1 WITH GRANT OPTION;
GRANT SELECT ON V_DOCUMENT_SCAN_AI_DOC_FILES TO WECO_TOWER1 WITH GRANT OPTION;
