DROP PACKAGE DOCUMENT_SCAN_AI_PKG;

DROP VIEW V_DOCUMENT_SCAN_AI_DOCUMENT_TYPES;
DROP VIEW V_DOCUMENT_SCAN_AI_JOB_DETAILS;
DROP VIEW V_DOCUMENT_SCAN_AI_DOC_DETAILS;
DROP VIEW V_DOCUMENT_SCAN_AI_DOC_FILES;
DROP VIEW V_DOCUMENT_SCAN_AI_KEY_VALUE;
DROP VIEW V_DOCUMENT_SCAN_AI_LINE_ITEM;
DROP VIEW V_DOCUMENT_SCAN_AI_INVOICES;
DROP VIEW V_DOCUMENT_SCAN_AI_LINE_ITEM_INVOICE;
DROP VIEW V_DOCUMENT_SCAN_AI_RECEIPTS;
DROP VIEW V_DOCUMENT_SCAN_AI_LINE_ITEM_RECEIPT;
DROP VIEW V_DOCUMENT_SCAN_AI_DRIVER_LICENSE;
DROP VIEW V_DOCUMENT_SCAN_AI_PASSPORT;
DROP VIEW V_DOCUMENT_SCAN_AI_TABLES;
DROP VIEW V_DOCUMENT_SCAN_AI_TEXT_LINE_VALUES;

DROP TABLE DOCUMENT_SCAN_AI_FIELD_TYPES CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_SCAN_AI_FIELD_ALIAS CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_SCAN_AI_LINE_ITEM_TYPES CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_SCAN_AI_LANGUAGES CASCADE CONSTRAINTS;

DROP TABLE DOCUMENT_SCAN_AI_CONFIG CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_SCAN_AI_JOBS CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_SCAN_AI_DOCS CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_SCAN_AI_FIELDS CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_SCAN_AI_TABLES CASCADE CONSTRAINTS;
